# Configuración del Software de Optimización Geométrica de Antenas (SOGA)

[physics]
# Constantes físicas
speed_of_light = 299792458.0  # Velocidad de la luz en m/s

[simulation]
# Parámetros de simulación por defecto
frequency_ghz = 2.4               # Frecuencia de operación en GHz (banda ISM 2.4 GHz - WiFi)
aperture_efficiency = 0.6         # Eficiencia de apertura típica (0-1)
beamwidth_k_factor = 65.0         # Factor k para cálculo de ancho de haz (IEEE Std 145-2013, típico)

# Modelo de peso realista: Peso_total = (densidad_reflector × área) + peso_fijo
reflector_areal_density_kg_per_m2 = 1.35  # Densidad del reflector parabólico (aluminio, fibra de vidrio)
fixed_component_weight_kg = 0.45           # Peso fijo: feed (0.2) + LNB (0.15) + soporte base (0.1) = 0.45 kg

# Parámetros del modelo de eficiencia de apertura vs f/D
# Basado en literatura (Balanis, Kraus)
efficiency_peak = 0.70            # Eficiencia máxima alcanzable (típica 65-70%)
optimal_f_d_ratio = 0.45          # Relación f/D óptima para máxima eficiencia
curvature_low_fd = 0.128          # Pérdida suave para f/D < óptimo (blockage)
curvature_high_fd = 0.236         # Pérdida pronunciada para f/D > óptimo (spillover)

[optimization]
# Parámetros del algoritmo de optimización NSGA-II
population_size = 40        # Tamaño de la población del algoritmo genético
max_generations = 80        # Número máximo de generaciones
seed = 1                    # Semilla para reproducibilidad

[user_defaults]
# Valores por defecto para parámetros de usuario
min_diameter_m = 0.1        # Diámetro mínimo de antena (metros)
max_diameter_m = 2.0        # Diámetro máximo de antena (metros)
max_payload_g = 1000.0      # Peso máximo permitido (gramos)
min_f_d_ratio = 0.3         # Relación focal mínima (adimensional)
max_f_d_ratio = 0.8         # Relación focal máxima (adimensional)
desired_range_km = 5.0      # Alcance de comunicación deseado (kilómetros)

[link_budget]
# Parámetros de link budget para validación de viabilidad de comunicación
# Referencias: ITU-R P.525, Friis Transmission Equation

# Parámetros del transmisor (TX)
tx_power_dbm = 20.0         # Potencia de transmisión típica para UAV: 20 dBm (100 mW)
                            # Rango típico: 10-30 dBm (10 mW - 1 W)
                            # Ref: TBS Crossfire (100mW-2W), ExpressLRS (50mW-1W)

# Parámetros del receptor (RX)
rx_sensitivity_dbm = -95.0  # Sensibilidad del receptor: -95 dBm
                            # Valores típicos:
                            # -85 dBm: Receptor básico de video analógico
                            # -95 dBm: Receptor estándar de telemetría
                            # -105 dBm: Receptor de alta sensibilidad
                            # -130 dBm: Receptor excepcional (TBS Crossfire)
                            # Ref: IEEE 802.15.4, ExpressLRS documentation

rx_noise_figure_db = 6.0    # Figura de ruido del receptor: 6 dB (típico)
                            # Rango típico: 3-10 dB
                            # Ref: Analog Devices RF receiver datasheets

# Requerimientos de señal
required_snr_db = 10.0      # SNR requerido para BER < 10^-3: 10 dB
                            # Valores según modulación:
                            # BPSK: 6-8 dB
                            # QPSK: 8-10 dB (asumido por defecto)
                            # 16-QAM: 14-16 dB
                            # Ref: "Digital Communications" Proakis & Salehi, 5th Ed.

# Márgenes de seguridad
fade_margin_db = 10.0       # Margen de desvanecimiento: 10 dB
                            # Compensa pérdidas por:
                            # - Clima (lluvia, niebla): 2-8 dB
                            # - Vegetación/obstáculos: 3-15 dB
                            # - Multipath fading: 5-10 dB
                            # Ref: ITU-R P.530, ITU-R P.833

implementation_loss_db = 3.0 # Pérdidas de implementación: 3 dB
                            # Incluye:
                            # - Pérdidas de cable/conectores: 0.5-2 dB
                            # - Desajuste de polarización: 0.5-3 dB
                            # - Tolerancias de fabricación: 0.5-1 dB
                            # Ref: IEEE Std 145-2013

# Factor de validación de viabilidad
min_link_margin_db = 6.0    # Margen mínimo de link budget para validación: 6 dB
                            # Un diseño profesional requiere margen positivo
                            # 0-3 dB: Marginal, poco confiable
                            # 3-6 dB: Aceptable, mínimo recomendado
                            # 6-10 dB: Bueno, recomendado para producción
                            # >10 dB: Excelente, robusto
                            # Ref: "Wireless Communications Principles and Practice" Rappaport

[regulatory]
# Límites regulatorios de la Agencia Nacional del Espectro (ANE) de Colombia
max_eirp_dbm = 36.0         # PIRE máximo permitido en dBm

[realistic_limits]
# Límites realistas para antenas parabólicas de 2.4 GHz
# Basados en restricciones prácticas de fabricación, portabilidad y operación
min_diameter_m = 0.05       # 5 cm: mínimo práctico para 2.4 GHz
max_diameter_m = 3.0        # 3 m: máximo práctico para aplicaciones portátiles
min_payload_g = 10.0        # 10 g: peso mínimo realista con estructura
max_payload_g = 5000.0      # 5 kg: máximo práctico para aplicaciones portátiles
min_f_d_ratio = 0.2         # Límite físico inferior (parábola profunda)
max_f_d_ratio = 1.5         # Límite físico superior (parábola muy plana)
min_range_km = 0.1          # 100 m: rango mínimo útil
max_range_km = 50.0         # 50 km: alcance máximo típico a 2.4 GHz
